### ISSUE TITLE
Why does does com.tagtraum.japlscript.execution.session repeat the tell application part

### ISSUE THREAD

**Issue by ijabz** [japlscript/japlscript#3]
I assumed that if you put multiple commands into one session there would be a single **tell application** at the start and an **end tell** at the end, but every fragment is wrapped with this.

Does this affect performance, wouldn't it be better to have just one tell at the start (as long as yo are only interacting with one application (as I am))

**Comment by hendriks73** [comment]
I am not sure multiple `tell`s in one AppleScript are detrimental to performance (haven't investigated or measured), but I am fairly certain that executing multiple AppleScripts instead of just one larger one is detrimental. That's why there is the Session  mechanism.

Feel free to set up a test that measures this, i.e. the overall impact of one or multiple `tell`s in one AppleScript. Don't forget that the logic that ensures only one application is talked to and the right AppleScript is generated also has to be executed.
